/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Library General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * SandNetPluginDescription.h
 * Contains the description for the sandnet plugin.
 * Copyright (C) 2016 Florian Edelmann
 *
 * This file has been autogenerated by convert_README_to_header.sh, DO NOT EDIT.
 */
#ifndef PLUGINS_SANDNET_SANDNETPLUGINDESCRIPTION_H_
#define PLUGINS_SANDNET_SANDNETPLUGINDESCRIPTION_H_

namespace ola {
namespace plugin {
namespace sandnet {

const char plugin_description[] = "SandNet Plugin\n"
"==============\n"
"\n"
"This plugin creates a single device with 2 output and 8 input ports.\n"
"\n"
"The universe bindings are offset by one from those displayed in sandnet. For\n"
"example, SandNet universe 1 is OLA universe 0.\n"
"\n"
"\n"
"## Config file: `ola-sandnet.conf`\n"
"\n"
"`ip = [a.b.c.d|<interface_name>]`  \n"
"The IP address or interface name to bind to. If not specified it will use\n"
"the first non-loopback interface.\n"
"\n"
"`name = ola-SandNet`  \n"
"The name of the node.";

}  // namespace sandnet
}  // namespace plugin
}  // namespace ola

#endif  // PLUGINS_SANDNET_SANDNETPLUGINDESCRIPTION_H_
