/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Library General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * ShowNetPluginDescription.h
 * Contains the description for the shownet plugin.
 * Copyright (C) 2016 Florian Edelmann
 *
 * This file has been autogenerated by convert_README_to_header.sh, DO NOT EDIT.
 */
#ifndef PLUGINS_SHOWNET_SHOWNETPLUGINDESCRIPTION_H_
#define PLUGINS_SHOWNET_SHOWNETPLUGINDESCRIPTION_H_

namespace ola {
namespace plugin {
namespace shownet {

const char plugin_description[] = "Strand ShowNet Plugin\n"
"=====================\n"
"\n"
"This plugin creates a single device with 8 input and 8 output ports.\n"
"\n"
"The ports correspond to the DMX channels used in the shownet protocol. For\n"
"example the first input and output port 0 is channels 1 - 512 and the second\n"
"input and output ports are channels 513 - 1024.\n"
"\n"
"\n"
"## Config file: `ola-shownet.conf`\n"
"\n"
"`ip = [a.b.c.d|<interface_name>]`  \n"
"The IP address or interface name to bind to. If not specified it will use\n"
"the first non-loopback interface.\n"
"\n"
"`name = ola-ShowNet`  \n"
"The name of the node.";

}  // namespace shownet
}  // namespace plugin
}  // namespace ola

#endif  // PLUGINS_SHOWNET_SHOWNETPLUGINDESCRIPTION_H_
