/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Library General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * GPIOPluginDescription.h
 * Contains the description for the gpio plugin.
 * Copyright (C) 2016 Florian Edelmann
 *
 * This file has been autogenerated by convert_README_to_header.sh, DO NOT EDIT.
 */
#ifndef PLUGINS_GPIO_GPIOPLUGINDESCRIPTION_H_
#define PLUGINS_GPIO_GPIOPLUGINDESCRIPTION_H_

namespace ola {
namespace plugin {
namespace gpio {

const char plugin_description[] = "General Purpose I/O Plugin\n"
"==========================\n"
"\n"
"This plugin controls the General Purpose Digital I/O (GPIO) pins on devices\n"
"like a Raspberry Pi. It creates a single device, with a single output port.\n"
"The offset (start address) of the GPIO pins is configurable.\n"
"\n"
"\n"
"## Config file: `ola-gpio.conf`\n"
"\n"
"`gpio_pins = [int]`  \n"
"The list of GPIO pins to control, each pin is mapped to a DMX512 slot.\n"
"\n"
"`gpio_slot_offset = <int>`  \n"
"The DMX512 slot for the first pin. Slots are indexed from 1.\n"
"\n"
"`gpio_turn_on = <int>`  \n"
"The DMX512 value above which a GPIO pin will be turned on.\n"
"\n"
"`gpio_turn_off = <int>`  \n"
"The DMX512 value below which a GPIO pin will be turned off.";

}  // namespace gpio
}  // namespace plugin
}  // namespace ola

#endif  // PLUGINS_GPIO_GPIOPLUGINDESCRIPTION_H_
