/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Library General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * MilInstPluginDescription.h
 * Contains the description for the milinst plugin.
 * Copyright (C) 2016 Florian Edelmann
 *
 * This file has been autogenerated by convert_README_to_header.sh, DO NOT EDIT.
 */
#ifndef PLUGINS_MILINST_MILINSTPLUGINDESCRIPTION_H_
#define PLUGINS_MILINST_MILINSTPLUGINDESCRIPTION_H_

namespace ola {
namespace plugin {
namespace milinst {

const char plugin_description[] = "Milford Instruments Plugin\n"
"==========================\n"
"\n"
"This plugin creates devices with one output port. It currently supports the\n"
"1-463 DMX Protocol Converter and 1-553 512 Channel Serial to DMX\n"
"Transmitter.\n"
"\n"
"\n"
"## Config file: `ola-milinst.conf`\n"
"\n"
"`device = /dev/ttyS0`  \n"
"The device to use as a path for the serial port. Multiple devices are\n"
"supported.\n"
"\n"
"### Per Device Settings\n"
"\n"
"`<device>-type = [1-463 | 1-553]`  \n"
"The type of interface.\n"
"\n"
"#### 1-553 Specific Per Device Settings\n"
"\n"
"`<device>-baudrate = [9600 | 19200]`  \n"
"The baudrate to connect at.\n"
"\n"
"`<device>-channels = [128 | 256 | 512]`  \n"
"The number of channels to send.";

}  // namespace milinst
}  // namespace plugin
}  // namespace ola

#endif  // PLUGINS_MILINST_MILINSTPLUGINDESCRIPTION_H_
