/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Library General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * FtdiDmxPluginDescription.h
 * Contains the description for the ftdidmx plugin.
 * Copyright (C) 2016 Florian Edelmann
 *
 * This file has been autogenerated by convert_README_to_header.sh, DO NOT EDIT.
 */
#ifndef PLUGINS_FTDIDMX_FTDIDMXPLUGINDESCRIPTION_H_
#define PLUGINS_FTDIDMX_FTDIDMXPLUGINDESCRIPTION_H_

namespace ola {
namespace plugin {
namespace ftdidmx {

const char plugin_description[] = "FTDI USB Chipset DMX Plugin\n"
"===========================\n"
"\n"
"This plugin is compatible with Enttec Open DMX USB and other FTDI chipset\n"
"based USB to DMX converters where the host needs to create the DMX stream\n"
"itself and not the interface (the interface has no microprocessor to do so).\n"
"\n"
"\n"
"## Config file: ola-ftdidmx.conf\n"
"\n"
"`frequency = 30`  \n"
"The DMX stream frequency (30 to 44 Hz max are the usual).";

}  // namespace ftdidmx
}  // namespace plugin
}  // namespace ola

#endif  // PLUGINS_FTDIDMX_FTDIDMXPLUGINDESCRIPTION_H_
