/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Library General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * NanoleafPluginDescription.h
 * Contains the description for the nanoleaf plugin.
 * Copyright (C) 2016 Florian Edelmann
 *
 * This file has been autogenerated by convert_README_to_header.sh, DO NOT EDIT.
 */
#ifndef PLUGINS_NANOLEAF_NANOLEAFPLUGINDESCRIPTION_H_
#define PLUGINS_NANOLEAF_NANOLEAFPLUGINDESCRIPTION_H_

namespace ola {
namespace plugin {
namespace nanoleaf {

const char plugin_description[] = "Nanoleaf Plugin\n"
"============\n"
"\n"
"This plugin creates a device per IP, each with one output port. Each port\n"
"represents a Nanoleaf Aurora controller, with up to 30 panels attached.\n"
"This plugin uses the streaming external control effects functionality of\n"
"the Aurora OpenAPI.\n"
"\n"
"Currently only the [Nanoleaf\n"
"Aurora](https://nanoleaf.me/en/consumer-led-lighting/products/\n"
"smarter-series/nanoleaf-light-panels-smarter-kit/)\n"
"is supported.\n"
"\n"
"\n"
"## Config file: `ola-nanoleaf.conf`\n"
"\n"
"`controller = <ip>`  \n"
"The IP of the controller to send to. You can communicate with more than\n"
"one controller by adding multiple `controller =` lines\n"
"\n"
"### Per Device Settings\n"
"\n"
"`<controller IP>-port = <int>`\n"
"The port to stream to on the controller, range is 1 - 65535.\n"
"\n"
"`<controller IP>-panels = [int]`\n"
"The list of panel IDs to control, each panel is mapped to three DMX512 slots\n"
"(for Red, Green and Blue).";

}  // namespace nanoleaf
}  // namespace plugin
}  // namespace ola

#endif  // PLUGINS_NANOLEAF_NANOLEAFPLUGINDESCRIPTION_H_
