/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Library General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * E131PluginDescription.h
 * Contains the description for the e131 plugin.
 * Copyright (C) 2016 Florian Edelmann
 *
 * This file has been autogenerated by convert_README_to_header.sh, DO NOT EDIT.
 */
#ifndef PLUGINS_E131_E131PLUGINDESCRIPTION_H_
#define PLUGINS_E131_E131PLUGINDESCRIPTION_H_

namespace ola {
namespace plugin {
namespace e131 {

const char plugin_description[] = "E1.31 (Streaming DMX over ACN) Plugin\n"
"=====================================\n"
"\n"
"This plugin creates a single device with a configurable number of input and\n"
"output ports.\n"
"\n"
"Each port can be assigned to a different E1.31 Universe.\n"
"\n"
"\n"
"## Config file: `ola-e131.conf`\n"
"\n"
"`cid = 00010203-0405-0607-0809-0A0B0C0D0E0F`  \n"
"The CID to use for this device.\n"
"\n"
"`dscp = [int]`  \n"
"The DSCP value to tag the packets with, range is 0 to 63.\n"
"\n"
"`draft_discovery = [bool]`  \n"
"Enable the draft (2014) E1.31 discovery protocol.\n"
"\n"
"`ignore_preview = [true|false]`  \n"
"Ignore preview data.\n"
"\n"
"`input_ports = [int]`  \n"
"The number of input ports to create up to an arbitrary max of 512.\n"
"\n"
"`ip = [a.b.c.d|<interface_name>]`  \n"
"The IP address or interface name to bind to. If not specified it will use\n"
"the first non-loopback interface.\n"
"\n"
"`output_ports = [int]`  \n"
"The number of output ports to create up to an arbitrary max of 512.\n"
"\n"
"`prepend_hostname = [true|false]`  \n"
"Prepend the hostname to the source name when sending packets.\n"
"\n"
"`revision = [0.2|0.46]`  \n"
"Select which revision of the standard to use when sending data. 0.2 is the\n"
"standardized revision, 0.46 (default) is the ANSI standard version.";

}  // namespace e131
}  // namespace plugin
}  // namespace ola

#endif  // PLUGINS_E131_E131PLUGINDESCRIPTION_H_
