/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Library General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * DummyPluginDescription.h
 * Contains the description for the dummy plugin.
 * Copyright (C) 2016 Florian Edelmann
 *
 * This file has been autogenerated by convert_README_to_header.sh, DO NOT EDIT.
 */
#ifndef PLUGINS_DUMMY_DUMMYPLUGINDESCRIPTION_H_
#define PLUGINS_DUMMY_DUMMYPLUGINDESCRIPTION_H_

namespace ola {
namespace plugin {
namespace dummy {

const char plugin_description[] = "Dummy Plugin\n"
"============\n"
"\n"
"The plugin creates a single device with one port. When used as an output\n"
"port it prints the first two bytes of dmx data to stdout.\n"
"\n"
"The Dummy plugin can also emulate a range of RDM devices. It supports the\n"
"following RDM device types:\n"
"\n"
"* Dummy Device (original)\n"
"* Dimmer Rack, with a configurable number of sub-devices\n"
"* Moving Light\n"
"* Advanced Dimmer Rack, with E1.37-1 PIDs\n"
"* A device that responds with ack timers\n"
"* Sensor Device, with a number of sensors implemented\n"
"* Network Device, with E1.37-2 PIDs\n"
"\n"
"The number of each type of device is configurable.\n"
"\n"
"\n"
"## Config file: `ola-dummy.conf`\n"
"\n"
"`ack_timer_count = 0`  \n"
"The number of ack timer responders to create.\n"
"\n"
"`advanced_dimmer_count = 0`  \n"
"The number of E1.37-1 dimmer responders to create.\n"
"\n"
"`dimmer_count = 1`  \n"
"The number of dimmer devices to create.\n"
"\n"
"`dimmer_subdevice_count = 1`  \n"
"The number of sub-devices each dimmer device should have.\n"
"\n"
"`dummy_device_count = 1`  \n"
"The number of dummy devices to create.\n"
"\n"
"`moving_light_count = 1`  \n"
"The number of moving light devices to create.\n"
"\n"
"`sensor_device_count = 1`  \n"
"The number of sensor-only devices to create.\n"
"\n"
"`network_device_count = 1`  \n"
"The number of network E1.37-2 devices to create.";

}  // namespace dummy
}  // namespace plugin
}  // namespace ola

#endif  // PLUGINS_DUMMY_DUMMYPLUGINDESCRIPTION_H_
