/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Library General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * StageProfiPluginDescription.h
 * Contains the description for the stageprofi plugin.
 * Copyright (C) 2016 Florian Edelmann
 *
 * This file has been autogenerated by convert_README_to_header.sh, DO NOT EDIT.
 */
#ifndef PLUGINS_STAGEPROFI_STAGEPROFIPLUGINDESCRIPTION_H_
#define PLUGINS_STAGEPROFI_STAGEPROFIPLUGINDESCRIPTION_H_

namespace ola {
namespace plugin {
namespace stageprofi {

const char plugin_description[] = "StageProfi Plugin\n"
"=================\n"
"\n"
"This plugin creates devices with one output port.\n"
"\n"
"\n"
"### Config file: `ola-stageprofi.conf`\n"
"\n"
"`device = /dev/ttyUSB0`  \n"
"`device = 192.168.1.250`  \n"
"The device to use either as a path for the USB version or an IP address for\n"
"the LAN version. Multiple devices are supported.";

}  // namespace stageprofi
}  // namespace plugin
}  // namespace ola

#endif  // PLUGINS_STAGEPROFI_STAGEPROFIPLUGINDESCRIPTION_H_
